// <auto-generated />
using System;
using FriendsSociety.Shaurya.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FriendsSociety.Shaurya.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250415144103_chatgpt_suggested_changes")]
    partial class chatgpt_suggested_changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.AbilityType", b =>
                {
                    b.Property<int>("AbilityTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbilityTypeID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbilityTypeID");

                    b.ToTable("AbilityTypes");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityID");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.ActivityCategory", b =>
                {
                    b.Property<int>("ActivityCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityCategoryID"));

                    b.Property<int>("AbilityTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ActivityID")
                        .HasColumnType("int");

                    b.Property<string>("ExclusionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityCategoryID");

                    b.HasIndex("AbilityTypeID");

                    b.HasIndex("ActivityID");

                    b.ToTable("ActivityCategories");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Ground", b =>
                {
                    b.Property<int>("GroundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroundID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroundID");

                    b.ToTable("Grounds");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.GroundAllocation", b =>
                {
                    b.Property<int>("GroundAllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroundAllocationID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroundID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("GroundAllocationID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("GroundID");

                    b.ToTable("GroundAllocations");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationID"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AbilityTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("AbilityTypeID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.ActivityCategory", b =>
                {
                    b.HasOne("FriendsSociety.Shaurya.Entities.AbilityType", "AbilityType")
                        .WithMany("ActivityCategories")
                        .HasForeignKey("AbilityTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsSociety.Shaurya.Entities.Activity", "Activity")
                        .WithMany("ActivityCategories")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityType");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.GroundAllocation", b =>
                {
                    b.HasOne("FriendsSociety.Shaurya.Entities.Activity", "Activity")
                        .WithMany("GroundAllocations")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsSociety.Shaurya.Entities.Ground", "Ground")
                        .WithMany("GroundAllocations")
                        .HasForeignKey("GroundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Ground");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.User", b =>
                {
                    b.HasOne("FriendsSociety.Shaurya.Entities.AbilityType", "AbilityType")
                        .WithMany("Users")
                        .HasForeignKey("AbilityTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FriendsSociety.Shaurya.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FriendsSociety.Shaurya.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AbilityType");

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.AbilityType", b =>
                {
                    b.Navigation("ActivityCategories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Activity", b =>
                {
                    b.Navigation("ActivityCategories");

                    b.Navigation("GroundAllocations");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Ground", b =>
                {
                    b.Navigation("GroundAllocations");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Organization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
