// <auto-generated />
using System;
using FriendsSociety.Shaurya.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FriendsSociety.Shaurya.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250415154358_added_seeder_class")]
    partial class added_seeder_class
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.AbilityType", b =>
                {
                    b.Property<int>("AbilityTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbilityTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbilityTypeID");

                    b.ToTable("AbilityTypes");

                    b.HasData(
                        new
                        {
                            AbilityTypeID = 1,
                            Description = "Partial or total inability to hear",
                            IsDeleted = false,
                            Name = "Hearing Impairment"
                        },
                        new
                        {
                            AbilityTypeID = 2,
                            Description = "Partial or total inability to see",
                            IsDeleted = false,
                            Name = "Visual Impairment"
                        },
                        new
                        {
                            AbilityTypeID = 3,
                            Description = "Difficulty walking or moving",
                            IsDeleted = false,
                            Name = "Mobility Impairment"
                        });
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityID"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityID");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityID = 1,
                            IsDeleted = false,
                            Name = "Wheelchair Basketball",
                            Rules = "Standard 5v5 rules apply"
                        },
                        new
                        {
                            ActivityID = 2,
                            IsDeleted = false,
                            Name = "Blind Running",
                            Rules = "Tethered guide required"
                        });
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.ActivityCategory", b =>
                {
                    b.Property<int>("ActivityCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityCategoryID"));

                    b.Property<int>("AbilityTypeID")
                        .HasColumnType("int");

                    b.Property<int>("ActivityID")
                        .HasColumnType("int");

                    b.Property<string>("ExclusionType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityCategoryID");

                    b.HasIndex("AbilityTypeID");

                    b.HasIndex("ActivityID");

                    b.ToTable("ActivityCategories");

                    b.HasData(
                        new
                        {
                            ActivityCategoryID = 1,
                            AbilityTypeID = 2,
                            ActivityID = 2
                        });
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Ground", b =>
                {
                    b.Property<int>("GroundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroundID"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroundID");

                    b.ToTable("Grounds");

                    b.HasData(
                        new
                        {
                            GroundID = 1,
                            Location = "City Sports Complex",
                            Name = "Main Arena"
                        },
                        new
                        {
                            GroundID = 2,
                            Location = "Community Park",
                            Name = "Open Ground"
                        });
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.GroundAllocation", b =>
                {
                    b.Property<int>("GroundAllocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroundAllocationID"));

                    b.Property<int>("ActivityID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroundID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("GroundAllocationID");

                    b.HasIndex("ActivityID");

                    b.HasIndex("GroundID");

                    b.ToTable("GroundAllocations");

                    b.HasData(
                        new
                        {
                            GroundAllocationID = 1,
                            ActivityID = 1,
                            EndTime = new DateTime(2025, 5, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            GroundID = 1,
                            StartTime = new DateTime(2025, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            GroundAllocationID = 2,
                            ActivityID = 2,
                            EndTime = new DateTime(2025, 5, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            GroundID = 2,
                            StartTime = new DateTime(2025, 5, 1, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationID"));

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationID");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            OrganizationID = 1,
                            Contact = "hope@example.org",
                            IsDeleted = false,
                            Name = "Hope Foundation"
                        });
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Name = "Participant",
                            Permissions = "ViewActivities"
                        },
                        new
                        {
                            RoleID = 2,
                            Name = "Volunteer",
                            Permissions = "ManageActivities,HelpParticipants"
                        });
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("AbilityTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("AbilityTypeID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("RoleID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            AbilityTypeID = 1,
                            Age = 24,
                            Contact = "arjun@example.com",
                            IsDeleted = false,
                            Name = "Arjun Mehta",
                            OrganizationID = 1,
                            RoleID = 1
                        },
                        new
                        {
                            UserID = 2,
                            AbilityTypeID = 2,
                            Age = 30,
                            Contact = "nikita@example.com",
                            IsDeleted = false,
                            Name = "Nikita Shah",
                            OrganizationID = 1,
                            RoleID = 2
                        });
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.ActivityCategory", b =>
                {
                    b.HasOne("FriendsSociety.Shaurya.Entities.AbilityType", "AbilityType")
                        .WithMany("ActivityCategories")
                        .HasForeignKey("AbilityTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsSociety.Shaurya.Entities.Activity", "Activity")
                        .WithMany("ActivityCategories")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbilityType");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.GroundAllocation", b =>
                {
                    b.HasOne("FriendsSociety.Shaurya.Entities.Activity", "Activity")
                        .WithMany("GroundAllocations")
                        .HasForeignKey("ActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FriendsSociety.Shaurya.Entities.Ground", "Ground")
                        .WithMany("GroundAllocations")
                        .HasForeignKey("GroundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Ground");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.User", b =>
                {
                    b.HasOne("FriendsSociety.Shaurya.Entities.AbilityType", "AbilityType")
                        .WithMany("Users")
                        .HasForeignKey("AbilityTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FriendsSociety.Shaurya.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FriendsSociety.Shaurya.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AbilityType");

                    b.Navigation("Organization");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.AbilityType", b =>
                {
                    b.Navigation("ActivityCategories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Activity", b =>
                {
                    b.Navigation("ActivityCategories");

                    b.Navigation("GroundAllocations");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Ground", b =>
                {
                    b.Navigation("GroundAllocations");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Organization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FriendsSociety.Shaurya.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
